
version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    depends_on:
      - mongo
    container_name: site-app
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    container_name: site-db
volumes:
 mongodb:
 


  

